apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: geozarr-convert
  namespace: devseed
  labels:
    app.kubernetes.io/name: geozarr-convert
    app.kubernetes.io/part-of: geozarr
    managed-by: argo
    example: "true"
spec:
  entrypoint: pipeline
  serviceAccountName: devseed
  workflowMetadata:
    labels:
      app.kubernetes.io/name: geozarr-convert
      app.kubernetes.io/part-of: geozarr
      example: "true"
  arguments:
    parameters:
      - name: image
        value: "ghcr.io/eopf-explorer/eopf-geozarr:dev"
      - name: stac_url
        value: "https://example.invalid/in.zarr"
      - name: output_zarr
        value: "/data/out.zarr"
      - name: groups
        value: "measurements/reflectance/r20m"
      - name: validate_groups
        value: "false"
      - name: register_url
        value: ""
      - name: register_collection
        value: ""
      - name: register_bearer_token
        value: ""
      - name: register_href
        value: ""
      # Optional S3-compatible endpoint for direct writes (e.g., OVHcloud)
      - name: s3_endpoint
        value: "https://s3.de.io.cloud.ovh.net"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
  # Tip: adjust storage size per dataset if needed.
  templates:
    - name: pipeline
      dag:
        tasks:
          - name: convert
            template: convert
            arguments:
              parameters:
                - { name: image, value: "{{workflow.parameters.image}}" }
                - { name: stac_url, value: "{{workflow.parameters.stac_url}}" }
                - { name: output_zarr, value: "{{workflow.parameters.output_zarr}}" }
                - { name: groups, value: "{{workflow.parameters.groups}}" }
                - { name: validate_groups, value: "{{workflow.parameters.validate_groups}}" }
                - { name: s3_endpoint, value: "{{workflow.parameters.s3_endpoint}}" }
          - name: register
            dependencies: [convert]
            template: register-stac
            arguments:
              parameters:
                - { name: image, value: "{{workflow.parameters.image}}" }
                - { name: output_zarr, value: "{{workflow.parameters.output_zarr}}" }
                - { name: register_href, value: "{{workflow.parameters.register_href}}" }
                - { name: register_url, value: "{{workflow.parameters.register_url}}" }
                - { name: register_collection, value: "{{workflow.parameters.register_collection}}" }
                - { name: register_bearer_token, value: "{{workflow.parameters.register_bearer_token}}" }
                - { name: s3_endpoint, value: "{{workflow.parameters.s3_endpoint}}" }

    - name: convert
      inputs:
        parameters:
          - name: image
          - name: stac_url
          - name: output_zarr
          - name: groups
          - name: validate_groups
          - name: s3_endpoint
      container:
        image: "{{inputs.parameters.image}}"
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: ovh-s3-creds
              optional: true
        command: [/bin/bash, -lc]
        args:
          - |
            set -euo pipefail

            STAC="{{inputs.parameters.stac_url}}"
            OUT="{{inputs.parameters.output_zarr}}"
            GROUPS_RAW="{{inputs.parameters.groups}}"
            VALIDATE="{{inputs.parameters.validate_groups}}"
            S3_ENDPOINT="{{inputs.parameters.s3_endpoint}}"
            PERF="/data/dask-report.html"

            echo "=== inputs ==="
            echo "stac_url=$STAC"
            echo "output_zarr=$OUT"
            echo "groups_raw=$GROUPS_RAW"
            echo "validate_groups=$VALIDATE"

            echo "=== env sanity ==="
            if ! command -v eopf-geozarr >/dev/null 2>&1; then
              echo "[error] eopf-geozarr not found on PATH";
              exit 127;
            fi

            # Normalize groups to absolute paths (accept comma or space separated)
            GROUP_LIST=""
            for g in $(printf '%s' "$GROUPS_RAW" | tr ',' ' '); do
              [ -z "$g" ] && continue
              case "$g" in /*) N="$g";; *) N="/$g";; esac
              GROUP_LIST="$GROUP_LIST $N"
            done
            GROUP_LIST="${GROUP_LIST# }"
            echo "groups_norm=$GROUP_LIST"

            if [ "$VALIDATE" = "true" ]; then
              echo "=== validate groups ==="
              for g in $GROUP_LIST; do
                if ! python -c 'import sys,xarray as xr; stac,grp=sys.argv[1:3]; dt=xr.open_datatree(stac, engine="zarr", consolidated=None); key=grp.strip("/"); _=dt[key]' "$STAC" "$g"; then
                  echo "[error] $g: missing or unreadable"
                  exit 64
                fi
              done
              echo "Groups OK: $GROUP_LIST"
            fi

            echo "=== convert ==="
            # Configure S3 endpoint for s3fs/boto if provided
            if [ -n "$S3_ENDPOINT" ]; then
              export AWS_S3_ENDPOINT="$S3_ENDPOINT"
              export AWS_ENDPOINT_URL="$S3_ENDPOINT"
            fi
            CMD=( eopf-geozarr convert "$STAC" "$OUT" --verbose )
            for g in $GROUP_LIST; do CMD+=( --groups "$g" ); done
            set -x
            "${CMD[@]}"
            set +x

        volumeMounts:
          - name: data
            mountPath: /data

    - name: register-stac
      inputs:
        parameters:
          - name: image
          - name: output_zarr
          - name: register_href
          - name: register_url
          - name: register_collection
          - name: register_bearer_token
          - name: s3_endpoint
      container:
        image: "{{inputs.parameters.image}}"
        imagePullPolicy: IfNotPresent
        command: [/bin/bash, -lc]
        args:
          - |
            set -euo pipefail

            OUT="{{inputs.parameters.output_zarr}}"
            HREF_OVERRIDE="{{inputs.parameters.register_href}}"
            URL="{{inputs.parameters.register_url}}"
            COLLECTION="{{inputs.parameters.register_collection}}"
            TOKEN="{{inputs.parameters.register_bearer_token}}"
            ENDPOINT="{{inputs.parameters.s3_endpoint}}"

            if [ -z "$URL" ]; then
              echo "No register_url provided; skipping STAC registration."
              exit 0
            fi
            if [ -z "$COLLECTION" ]; then
              echo "register_url provided but register_collection is empty; skipping registration."
              exit 0
            fi

            ITEM_ID="$(basename "$OUT" | sed 's/\.[^.]*$//')"
            if [ -n "$HREF_OVERRIDE" ]; then
              HREF_PLACEHOLDER="$HREF_OVERRIDE"
            else
              # If output is s3://bucket/key and endpoint is provided, derive an https-style URL
              if printf '%s' "$OUT" | grep -q '^s3://'; then
                if [ -n "$ENDPOINT" ]; then
                  PATH_NO_SCHEME="${OUT#s3://}"
                  BUCKET="${PATH_NO_SCHEME%%/*}"
                  KEY="${PATH_NO_SCHEME#*/}"
                  HREF_PLACEHOLDER="${ENDPOINT%/}/$BUCKET/$KEY"
                else
                  HREF_PLACEHOLDER="$OUT"
                fi
              else
                HREF_PLACEHOLDER="$OUT"
              fi
            fi
            ITEM_JSON="/data/${ITEM_ID}.item.json"

            echo "=== build minimal STAC Item ==="
            printf '%s\n' \
              '{' \
              '  "type": "Feature",' \
              '  "stac_version": "1.0.0",' \
              "  \"id\": \"${ITEM_ID}\"," \
              "  \"collection\": \"${COLLECTION}\"," \
              '  "geometry": null,' \
              '  "bbox": null,' \
              '  "properties": {},' \
              '  "assets": {' \
              '    "data": {' \
              "      \"href\": \"${HREF_PLACEHOLDER}\"," \
              '      "type": "application/vnd+zarr",' \
              '      "roles": ["data"],' \
              '      "title": "GeoZarr dataset"' \
              '    }' \
              '  },' \
              '  "links": []' \
              '}' \
              > "$ITEM_JSON"

            echo "Wrote $ITEM_JSON"

            echo "=== POST to STAC Transactions (if supported) ==="
            HDRS=("Content-Type: application/json")
            if [ -n "$TOKEN" ]; then
              HDRS+=("Authorization: Bearer $TOKEN")
            fi
            set -x
            curl -fsS -X POST "${URL%/}/collections/${COLLECTION}/items" \
              "${HDRS[@]/#/-H }" \
              --data-binary "@${ITEM_JSON}" \
              -o /data/register-response.json
            set +x
            echo "Registration response saved to /data/register-response.json"
        volumeMounts:
          - name: data
            mountPath: /data

  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodCompletion
