apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: geozarr-convert
spec:
  entrypoint: geozarr-convert
  serviceAccountName: default
  arguments:
    parameters:
      - name: image
        value: "eopf-geozarr:dev"
      - name: pvc_name
        value: "geozarr-pvc"
      - name: stac_url
        value: "https://example.invalid/in.zarr"
      - name: output_zarr
        value: "/data/out.zarr"
      - name: groups
        value: "measurements/reflectance/r20m"
      - name: validate_groups
        value: "false"
  templates:
    - name: geozarr-convert
      inputs:
        parameters:
          - name: image
          - name: pvc_name
          - name: stac_url
          - name: output_zarr
          - name: groups
          - name: validate_groups
      container:
        image: "{{inputs.parameters.image}}"
        imagePullPolicy: IfNotPresent
        command: [bash, -lc]
        args:
          - |
            set -euo pipefail
            bash /app/scripts/convert.sh               --stac-url "{{inputs.parameters.stac_url}}"               --output-zarr "{{inputs.parameters.output_zarr}}"               --groups "{{inputs.parameters.groups}}"               --validate-groups "{{inputs.parameters.validate_groups}}"
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "{{inputs.parameters.pvc_name}}"
