apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: geozarr-amqp
  namespace: devseed
spec:
  amqp:
    stac-items:
      url: "amqps://<user>:<pass>@<host>:<port>/<vhost>"
      exchangeType: topic
      exchangeName: stac.search
      routingKey: "items.#"
      connectionBackoff:
        duration: 5s
      jsonBody: true
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: geozarr-stac-sensor
  namespace: devseed
spec:
  dependencies:
    - name: stac-items
      eventSourceName: geozarr-amqp
    eventName: stac-items
  # TODO: set your real RabbitMQ URL and vhost in the EventSource above.
  triggers:
    - template:
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: Workflow
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: geozarr-convert-
                namespace: devseed
              spec:
                entrypoint: pipeline
                workflowTemplateRef:
                  name: geozarr-convert
                arguments:
                  parameters:
                    - name: stac_url
                      value: "{{eventBody.properties.href}}"
                    - name: output_zarr
                      value: "/data/{{sprig.trimSuffix \".zarr\" (sprig.basename (index eventBody \"properties\" \"href\"))}}_geozarr.zarr"
                    - name: groups
                      value: "{{eventBody.properties.groups}}"
                    - name: register_url
                      value: "{{eventBody.properties.register_url}}"
                    - name: register_collection
                      value: "{{eventBody.properties.collection}}"
                    - name: register_bearer_token
                      value: ""
                    - name: s3_endpoint
                      value: "https://s3.de.io.cloud.ovh.net"
          parameters:
            - src:
                dependencyName: stac-items
                dataKey: body
              dest: spec.arguments.parameters
